### ISSUE TITLE
Test browser

### ISSUE THREAD

**Issue by tobinski** [dataramblers/datenhack-frontend#1]
Aktuell ist [brave](https://brave.com/) als Browser für die Testsuite definiert. Ich schlage vor dies auf Chrome oder Chrome-headless zu ändern.

**Comment by sschuepbach** [comment]
Ich habe den Testbrowser geändert, da ich eine Linux-Distro benutze, die Chrome/Chromium nicht in ihren Paket-Repositorien anbietet. Wir können das aber gerne wieder rückgängig machen.

**Comment by sschuepbach** [comment]
Rückgängig gemacht per 8373b86b093749c4bb192cec87f8dce7899b04bf
