### ISSUE TITLE
Angular-Eigenentwicklung versus Afrika-Portal?

### ISSUE THREAD

**Issue by notand** [dataramblers/datenhack-frontend#2]
Info per Email von @martrei am 07.02.:
Franck sieht eigentlich kein grosses Problem, dass wir die Afrikaportal/RDV-Entwicklungen nachnutzen, weiterentwickeln und möglicherweise bereits vor dem Start des Afrika-Portals beim Hackathon präsentieren. In den nächsten Tagen würde ich wohl mal die Oberfläche anbinden. Es handelt sich dabei aber wirklich nur um einen ersten Prototyp, bei dem öfter mal etwas nicht wie erwartet funktioniert.

Sollten wir uns die Afrika-Portal-Entwicklung anschauen und dann entscheiden, ob wir damit oder mit der Angular-Neuprogrammierung (dieses Repository) weiter fahren? @martrei: Wo können wir uns die Afrika-Portal-Entwicklungen anschauen? (Code und/oder Beispiel aus Nutzungssicht)

**Comment by tobinski** [comment]
Ich würde gerne einen Blick auf das Afrika-Portal werfen und falls wir das sinnvoll nutzen können wäre das sicher sinnvoll. Wie sieht es denn mit Lizenzen aus? Könnten wir das ganze öffentlich entwickeln?

**Comment by ubunibas** [comment]
Habe es heute nochmal abgeklärt: das Repo ist hier nun frei zugänglich: https://github.com/UB-UNIBAS/rdv. 
Ich hoffe, dass ich diese Woche/Wochenende dazukomme, die neuen Daten in Elasticsearch zu laden und die Oberfläche anzubinden.

**Comment by tobinski** [comment]
@ubunibas Besten Dank für das Repo! Ich werde in den kommenden Tagen einen Blick rein werfen und Rückmeldung geben.

**Comment by notand** [comment]
Ich habe versucht, das Afrikaportal bei mir lokal zu starten, bekomme auf ng serve aber untenstehende Fehlermeldung. Hat jemand einen Tip, ob das am derzeitigen Stand des Repos liegt, oder ob ich bei mir irgendwas machen kann/muss, evtl. mit bootstrap oder mit meinem Browser (Firefox)?
ERROR in ./ ~ /css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/bootstrap/dist/css/bootstrap.min.css
Module build failed: BrowserslistError: Unknown browser major
    at error (/home/andrea/gits/rdv/node_modules/browserslist/index.js:37:11)
    at Function.browserslist.checkName (/home/andrea/gits/rdv/node_modules/browserslist/index.js:320:18)
    at Function.select (/home/andrea/gits/rdv/node_modules/browserslist/index.js:438:37)
    at /home/andrea/gits/rdv/node_modules/browserslist/index.js:207:41
    at Array.forEach (<anonymous>)
    at browserslist (/home/andrea/gits/rdv/node_modules/browserslist/index.js:196:13)
    at Browsers.parse (/home/andrea/gits/rdv/node_modules/autoprefixer/lib/browsers.js:44:14)
    at new Browsers (/home/andrea/gits/rdv/node_modules/autoprefixer/lib/browsers.js:39:28)
    at loadPrefixes (/home/andrea/gits/rdv/node_modules/autoprefixer/lib/autoprefixer.js:56:18)
    at plugin (/home/andrea/gits/rdv/node_modules/autoprefixer/lib/autoprefixer.js:62:18)
    at LazyResult.run (/home/andrea/gits/rdv/node_modules/postcss/lib/lazy-result.js:274:20)
    at LazyResult.asyncTick (/home/andrea/gits/rdv/node_modules/postcss/lib/lazy-result.js:189:32)
    at LazyResult.asyncTick (/home/andrea/gits/rdv/node_modules/postcss/lib/lazy-result.js:201:22)
    at processing.Promise.then._this2.processed (/home/andrea/gits/rdv/node_modules/postcss/lib/lazy-result.js:228:20)
    at new Promise (<anonymous>)
    at LazyResult.async (/home/andrea/gits/rdv/node_modules/postcss/lib/lazy-result.js:225:27)
 @ ./ ~ /bootstrap/dist/css/bootstrap.min.css 4:14-127
 @ multi ./src/styles.css ./ ~ /bootstrap/dist/css/bootstrap.min.css ./ ~ /font-awesome/css/font-awesome.css ./ ~ /ion-rangeslider/css/ion.rangeSlider.css ./ ~ /ion-rangeslider/css/ion.rangeSlider.skinFlat.css
webpack: Failed to compile.

**Comment by sschuepbach** [comment]
@notand, es handelt sich wohl um ein Problem mit der verwendeten Version von angular-cli (für Details: https://github.com/angular/angular-cli/issues/9020). Bei mir hat es funktioniert, als ich in `package.json` die Version von angular-cli auf die jüngste der 1.x-Reihe erhöht habe (`1.7.1`).

Im Übrigen bin auch ich dafür, dass wir uns das Afrikaportal zuerst genauer anschauen, bevor wir Dinge doppelt machen. Ich denke, dass wir gerade im Bereich der ES-Services einiges wiederverwenden können.

**Comment by martrei** [comment]
@notand  das hatte ich ganz verdrängt:

- npm remove  bootstrap@4.0.0-beta
- npm install bootstrap@4.0.0-beta.2

hat bei mir damals geholfen.

**Comment by tobinski** [comment]
@martrei Bootstrap gibt es mittlerweile als stabiles Paket.

**Comment by notand** [comment]
@sschuepbach @martrei Danke für eure Hinweise. Ich hatte ein bisschen Gewurschtel und Neu-Heruminstallierung von Angular CLI, aber nun läufts mit der von Sebastian angegebenen Dependency-Änderung. Das sieht ja interessant aus!

**Comment by tobinski** [comment]
Ich hab nun auch die Zeit gefunden einen Blick in das RDV Projekt zu werfen. Hier meine ersten Eindrücke zu dem Projekt.

**pro RDV**

- Es existiert bereits
- Neue Features würden (hoffentlich) direkt in ein aktives Projekt zurückfliessen
- Es deckt einige unserer Usecases ab: Filtern, Facetten, Suche Speichern, Sortieren?
- Viele Comments, die bei der Orientierung helfen

**contra RDV**

- Fehlende Tests (machen wir welche?) https://github.com/UB-UNIBAS/rdv/issues/5
- Nicht stark modularisiert . Gerade die Suche ist eine sehr grosse Einzel-Komponente, die auch schwer zu testen ist. 
- Grössere Einarbeitungszeit. 

**Unklar**

- Datenstruktur: Mir ist hier noch einiges unklar, was wie funktioniert. Dafür brauche ich mehr Zeit mir den Code anzuschauen. So auch die Frage wie einfach unsere Daten zu implementieren sind.
- Backend: Die Datenstruktur des Elastic Search Instanz kann aktuell noch nicht angeschaut werden. https://github.com/UB-UNIBAS/rdv/issues/3

**Comment by martrei** [comment]
Sorry, dass ich jetzt erst dazukomme mich zu melden. Es ist auf jeden Fall sehr spannend die ganzen Ueberlegungen zu lesen. Ich freu mich schon richtig auf das Projekt, weil ich das Gefühl habe, dass ich dabei eine Menge lernen kann.
Wäre es aber vielleicht gut, wenn wir uns einmal treffen würden, dann könnten wir auch besser über die Hydra-API / Afrikaportal-Entscheidung und das weitere Vorgehen sprechen?

Ganz kurz aber das Afrikaportal konzeptionell zusammengefasst: 

- Frontendseitig ist die  Idee  eine Applikation zu haben, die so frei konfigurierbar ist, dass diese an diverse ES-Datensets angebunden werden und einfach funktional ergänzt werden kann. (Dieses Ziel würde ja eigentlich sogar für die API-Plattform sprechen, aber ich bin mir nicht sicher, ob dafür die Entwicklung nicht bereits zu weit fortgeschritten ist)

- Backendseitig: heterogene, (relativ einfach strukturierte) Daten durch diverse Tools (Google Spreadsheets, OpenRefine, Kibana) serverseitig mappen, analysieren, bereinigen, anzureichern und idealerweise dezentral einspielen/aktualisieren zu können. Mal schauen, was davon klappt :-)

Das Datenmodell dahinter ist momentan (auch bedingt durch die Ursprungsdaten) sehr flach und selbstgestrickt. Für Inputs gerade hinsichtlich JSON-LD wäre ich aber sehr dankbar. Prinzipiell haben wir die Datenmodell-Diskussion momentan eher aufgeschoben. Die Hintergründe kann ich gerne mündlich mal erklären :-)

Das momentane Stadium ist pre-alpha. Bislang haben wir den Backend-Teil und den Frontend-Teil getrennt voneinander entwickelt. In den nächsten Wochen wollen wir uns aber mal zusammensetzen, um über das weitere Vorgehen zu sprechen. Angedacht ist eigentlich noch eine Ueberarbeitung der Detailseiten, eine Kartenanwendung und auch eine graphische Ueberarbeitung der Applikation.

**Comment by tobinski** [comment]
@martrei Ich denke es würde Sinn  machen sich mal zu treffen und genauer zu diskutieren. Wann wird wohl die grosse Frage sein... Aktuell stehen einfach zu viele Optionen im Raum und wir treffen keine wirkliche Entscheidungen.

**Comment by sschuepbach** [comment]
@martrei, @tobinski: Ich habe soeben ein Mail für ein [gemeinsames Treffen](https://github.com/dataramblers/datenhack-sozarchiv/wiki/2.-Projekttreffen) verschickt.

**Comment by tobinski** [comment]
@notand können wir dies schliessen? An dem gemeinsamen Treffen haben wir entschieden vorläufig was eigenes zu machen
